# Generated by Django 3.2.16 on 2025-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default='<built-in method today of type object at 0x1031f79d0>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default='<built-in method today of type object at 0x1031f79d0>'),
        ),
    ]
